#!/bin/bash
_nodeModulesBin="./node_modules/.bin"
_composerVendorBin="./vendor/bin"
_VERSION="1.0"
PATH="$_nodeModulesBin:$_composerVendorBin:$PATH"

function _banner(){
    cat << "EOF"

   / /_  ____ _/ /_____  / __(_) /__  
  / __ \/ __ `/ //_/ _ \/ /_/ / / _ \
 / /_/ / /_/ / ,< /  __/ __/ / /  __/
/_.___/\__,_/_/|_|\___/_/ /_/_/\___/ 
EOF
    cat << EOF
Version: $_VERSION
User: $(whoami)
PWD: $PWD

EOF

}

function _default {
    start
}

function install {
    echo "install recipe not implemented"
}

function build {
    echo "build recipe not implemented"
}

function start {
    echo "start recipe not implemented"
}



function help {
    printf "$0 <recipe> <args>\n\n"
    printf "Recipes:\n"
    compgen -A function | grep -v '^_' | cat -n
}

TIMEFORMAT=$'\nRecipe completed in %3lR'
_banner
time ${@:-_default}